import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:cl_spreadsheet/store/cell_data.dart';
import 'package:cl_spreadsheet/store/spreadsheet_db.dart';
import 'package:cl_spreadsheet/store/spread_sheet.dart';
import 'package:cl_spreadsheet/grid_layout.dart'; // Import CheckboxGridId

import 'spread_sheet_test.mocks.dart'; // Generated by build_runner

@GenerateMocks([SpreadsheetDB])
void main() {
  group('SpreadSheet', () {
    late MockSpreadsheetDB mockDb;

    setUp(() {
      mockDb = MockSpreadsheetDB();
    });

    test('load should initialize SpreadSheet with data from DB', () async {
      final dbRawData = {
        CheckboxGridId(row: 0, column: 0): CellData(value: 'Header 0', properties: {}),
        CheckboxGridId(row: 0, column: 1): CellData(value: 'Header 1', properties: {}),
        CheckboxGridId(row: 1, column: 0): CellData(value: 'Value 0,0', properties: {}),
        CheckboxGridId(row: 1, column: 1): CellData(value: 'Value 0,1', properties: {}),
      };

      when(mockDb.readAll()).thenAnswer((_) async => dbRawData);

      final spreadSheet = await SpreadSheet.load(mockDb);

      expect(spreadSheet.data, dbRawData);
      expect(spreadSheet.db, mockDb);
      verify(mockDb.readAll()).called(1);
    });

    test('reload should fetch fresh data from DB', () async {
      final initialDbRawData = {
        CheckboxGridId(row: 0, column: 0): CellData(value: 'Old', properties: {}),
      };
      final newDbRawData = {
        CheckboxGridId(row: 0, column: 0): CellData(value: 'New', properties: {}),
      };

      // First call to readAll returns initialDbRawData
      when(mockDb.readAll()).thenAnswer((_) async => initialDbRawData);

      final spreadSheet = await SpreadSheet.load(mockDb);
      expect(spreadSheet.data, initialDbRawData);

      // Second call to readAll returns newDbRawData
      when(
        mockDb.readAll(),
      ).thenAnswer((_) async => newDbRawData); // This line is the change

      final reloadedSpreadSheet = await spreadSheet.reload();
      expect(reloadedSpreadSheet.data, newDbRawData);
      expect(
        reloadedSpreadSheet,
        isNot(same(spreadSheet)),
      ); // Should be a new instance
      verify(mockDb.readAll()).called(2);
    });

    group('upsertOrDelete', () {
      test(
        'should upsert a cell and return a new SpreadSheet instance',
        () async {
          final initialSpreadSheetData = {
            CheckboxGridId(row: 0, column: 0): CellData(value: 'Old', properties: {}),
          };
          final newCellData = CellData(
            value: 'New',
            properties: {'style': 'bold'},
          );
          final id = CheckboxGridId(row: 0, column: 1);

          final spreadSheet = SpreadSheet(db: mockDb, data: initialSpreadSheetData);

          when(mockDb.upsert(id, newCellData)).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            id,
            newCellData,
          );

          expect(updatedSpreadSheet.read(id), newCellData);
          expect(
            updatedSpreadSheet.read(CheckboxGridId(row: 0, column: 0)),
            initialSpreadSheetData[CheckboxGridId(row: 0, column: 0)],
          ); // Other data should remain
          expect(
            updatedSpreadSheet,
            isNot(same(spreadSheet)),
          ); // Should be a new instance
          verify(mockDb.upsert(id, newCellData)).called(1);
        },
      );

      test(
        'should update an existing cell and return a new SpreadSheet instance',
        () async {
          final initialSpreadSheetData = {
            CheckboxGridId(row: 0, column: 0): CellData(value: 'Old', properties: {}),
          };
          final updatedCellData = CellData(
            value: 'Updated',
            properties: {'style': 'italic'},
          );
          final id = CheckboxGridId(row: 0, column: 0);

          final spreadSheet = SpreadSheet(db: mockDb, data: initialSpreadSheetData);

          when(
            mockDb.upsert(id, updatedCellData),
          ).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            id,
            updatedCellData,
          );

          expect(updatedSpreadSheet.read(id), updatedCellData);
          expect(
            updatedSpreadSheet,
            isNot(same(spreadSheet)),
          ); // Should be a new instance
          verify(mockDb.upsert(id, updatedCellData)).called(1);
        },
      );

      test(
        'should delete a cell and return a new SpreadSheet instance',
        () async {
          final initialSpreadSheetData = {
            CheckboxGridId(row: 0, column: 0): CellData(value: 'To Delete', properties: {}),
          };
          final id = CheckboxGridId(row: 0, column: 0);

          final spreadSheet = SpreadSheet(db: mockDb, data: initialSpreadSheetData);

          when(mockDb.delete(id)).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            id,
            null,
          );

          expect(updatedSpreadSheet.read(id), isNull);
          expect(
            updatedSpreadSheet.data.containsKey(id),
            isFalse,
          ); // Cell should be removed
          expect(
            updatedSpreadSheet,
            isNot(same(spreadSheet)),
          ); // Should be a new instance
          verify(mockDb.delete(id)).called(1);
        },
      );

      test('should delete a cell and keep other cells in the row', () async {
        final initialSpreadSheetData = {
          CheckboxGridId(row: 0, column: 0): CellData(value: 'To Delete', properties: {}),
          CheckboxGridId(row: 0, column: 1): CellData(value: 'Keep Me', properties: {}),
        };
        final idToDelete = CheckboxGridId(row: 0, column: 0);
        final idToKeep = CheckboxGridId(row: 0, column: 1);

        final spreadSheet = SpreadSheet(db: mockDb, data: initialSpreadSheetData);

        when(mockDb.delete(idToDelete)).thenAnswer((_) async => {});

        final updatedSpreadSheet = await spreadSheet.upsertOrDelete(idToDelete, null);

        expect(updatedSpreadSheet.read(idToDelete), isNull);
        expect(
          updatedSpreadSheet.read(idToKeep),
          initialSpreadSheetData[idToKeep],
        ); // Other cell should remain
        expect(
          updatedSpreadSheet.data.containsKey(idToKeep),
          isTrue,
        ); // Other cell should remain
        expect(
          updatedSpreadSheet,
          isNot(same(spreadSheet)),
        ); // Should be a new instance
        verify(mockDb.delete(idToDelete)).called(1);
      });

      test(
        'should return same SpreadSheet instance if deleting non-existent cell',
        () async {
          final initialSpreadSheetData = {
            CheckboxGridId(row: 0, column: 0): CellData(value: 'Existing', properties: {}),
          };
          final existingId = CheckboxGridId(row: 0, column: 0);
          final nonExistentId = CheckboxGridId(row: 0, column: 1);

          final spreadSheet = SpreadSheet(db: mockDb, data: initialSpreadSheetData);

          // Mock DB delete to do nothing as cell doesn't exist in DB either
          when(mockDb.delete(nonExistentId)).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            nonExistentId,
            null,
          );

          expect(updatedSpreadSheet.read(existingId), initialSpreadSheetData[existingId]);
          expect(updatedSpreadSheet.read(nonExistentId), isNull);
          expect(
            updatedSpreadSheet,
            same(spreadSheet),
          ); // Should be the same instance
          verifyNever(
            mockDb.delete(any),
          ); // Should not call delete on DB if not in local data
        },
      );
    });

    test('read should return CellData if present', () {
      final cell = CellData(value: 'Test', properties: {});
      final id = CheckboxGridId(row: 0, column: 0);
      final data = {
        id: cell,
      };
      final spreadSheet = SpreadSheet(db: mockDb, data: data);

      expect(spreadSheet.read(id), cell);
    });

    test('read should return null if cell not present', () {
      final data = {
        CheckboxGridId(row: 0, column: 0): CellData(value: 'Test', properties: {}),
      };
      final id = CheckboxGridId(row: 0, column: 1);
      final spreadSheet = SpreadSheet(db: mockDb, data: data);

      expect(spreadSheet.read(id), isNull);
    });

    test('operator == and hashCode should work correctly', () {
      final db1 = MockSpreadsheetDB();
      final db2 = MockSpreadsheetDB();
      final data1 = {
        CheckboxGridId(row: 0, column: 0): CellData(value: 'A', properties: {}),
      };
      final data3 = {
        CheckboxGridId(row: 0, column: 0): CellData(value: 'B', properties: {}),
      };

      final ss1 = SpreadSheet(db: db1, data: data1);
      final ss2 = SpreadSheet(db: db1, data: data1);
      final ss3 = SpreadSheet(db: db1, data: data3);
      final ss4 = SpreadSheet(db: db2, data: data1);

      expect(ss1, ss2);
      expect(ss1.hashCode, ss2.hashCode);
      expect(ss1, isNot(ss3));
      expect(ss1, isNot(ss4));
    });
  });
}
