// Mocks generated by Mockito 5.4.6 from annotations
// in cl_spreadsheet/test/store/spread_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cl_spreadsheet/models/store/cell_data.dart' as _i6;
import 'package:cl_spreadsheet/models/store/checkbox_grid_id.dart' as _i5;
import 'package:cl_spreadsheet/models/store/spreadsheet_db.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqlite_async/sqlite_async.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSqliteDatabase_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeSqliteDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpreadsheetDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpreadsheetDB extends _i1.Mock implements _i3.SpreadsheetDB {
  MockSpreadsheetDB() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeSqliteDatabase_0(this, Invocation.getter(#db)),
          )
          as _i2.SqliteDatabase);

  @override
  _i4.Future<void> upsert(_i5.CheckboxGridId? id, _i6.CellData? cellData) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [id, cellData]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.CellData?> read(_i5.CheckboxGridId? id) =>
      (super.noSuchMethod(
            Invocation.method(#read, [id]),
            returnValue: _i4.Future<_i6.CellData?>.value(),
          )
          as _i4.Future<_i6.CellData?>);

  @override
  _i4.Future<void> delete(_i5.CheckboxGridId? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<_i5.CheckboxGridId, _i6.CellData>> readAll() =>
      (super.noSuchMethod(
            Invocation.method(#readAll, []),
            returnValue:
                _i4.Future<Map<_i5.CheckboxGridId, _i6.CellData>>.value(
                  <_i5.CheckboxGridId, _i6.CellData>{},
                ),
          )
          as _i4.Future<Map<_i5.CheckboxGridId, _i6.CellData>>);
}
