import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:cl_spreadsheet/store/cell_data.dart';
import 'package:cl_spreadsheet/store/spreadsheet_db.dart';
import 'package:cl_spreadsheet/store/spread_sheet.dart';

import 'spread_sheet_test.mocks.dart'; // Generated by build_runner

@GenerateMocks([SpreadsheetDB])
void main() {
  group('SpreadSheet', () {
    late MockSpreadsheetDB mockDb;

    setUp(() {
      mockDb = MockSpreadsheetDB();
    });

    test('load should initialize SpreadSheet with data from DB', () async {
      final initialData = {
        0: {
          0: CellData(value: 'Header 0', properties: {}),
          1: CellData(value: 'Header 1', properties: {}),
        },
        1: {
          0: CellData(value: 'Value 0,0', properties: {}),
          1: CellData(value: 'Value 0,1', properties: {}),
        },
      };

      when(mockDb.readAll()).thenAnswer((_) async => initialData);

      final spreadSheet = await SpreadSheet.load(mockDb);

      expect(spreadSheet.data, initialData);
      expect(spreadSheet.db, mockDb);
      verify(mockDb.readAll()).called(1);
    });

    test('reload should fetch fresh data from DB', () async {
      final initialData = {
        0: {0: CellData(value: 'Old', properties: {})},
      };
      final newData = {
        0: {0: CellData(value: 'New', properties: {})},
      };

      // First call to readAll returns initialData
      when(mockDb.readAll()).thenAnswer((_) async => initialData);

      final spreadSheet = await SpreadSheet.load(mockDb);
      expect(spreadSheet.data, initialData);

      // Second call to readAll returns newData
      when(
        mockDb.readAll(),
      ).thenAnswer((_) async => newData); // This line is the change

      final reloadedSpreadSheet = await spreadSheet.reload();
      expect(reloadedSpreadSheet.data, newData);
      expect(
        reloadedSpreadSheet,
        isNot(same(spreadSheet)),
      ); // Should be a new instance
      verify(mockDb.readAll()).called(2);
    });

    group('upsertOrDelete', () {
      test(
        'should upsert a cell and return a new SpreadSheet instance',
        () async {
          final initialData = {
            0: {0: CellData(value: 'Old', properties: {})},
          };
          final newCellData = CellData(
            value: 'New',
            properties: {'style': 'bold'},
          );

          final spreadSheet = SpreadSheet(db: mockDb, data: initialData);

          when(mockDb.upsert(0, 1, newCellData)).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            0,
            1,
            newCellData,
          );

          expect(updatedSpreadSheet.read(0, 1), newCellData);
          expect(
            updatedSpreadSheet.read(0, 0),
            initialData[0]![0],
          ); // Other data should remain
          expect(
            updatedSpreadSheet,
            isNot(same(spreadSheet)),
          ); // Should be a new instance
          verify(mockDb.upsert(0, 1, newCellData)).called(1);
        },
      );

      test(
        'should update an existing cell and return a new SpreadSheet instance',
        () async {
          final initialData = {
            0: {0: CellData(value: 'Old', properties: {})},
          };
          final updatedCellData = CellData(
            value: 'Updated',
            properties: {'style': 'italic'},
          );

          final spreadSheet = SpreadSheet(db: mockDb, data: initialData);

          when(
            mockDb.upsert(0, 0, updatedCellData),
          ).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            0,
            0,
            updatedCellData,
          );

          expect(updatedSpreadSheet.read(0, 0), updatedCellData);
          expect(
            updatedSpreadSheet,
            isNot(same(spreadSheet)),
          ); // Should be a new instance
          verify(mockDb.upsert(0, 0, updatedCellData)).called(1);
        },
      );

      test(
        'should delete a cell and return a new SpreadSheet instance',
        () async {
          final initialData = {
            0: {0: CellData(value: 'To Delete', properties: {})},
          };

          final spreadSheet = SpreadSheet(db: mockDb, data: initialData);

          when(mockDb.delete(0, 0)).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            0,
            0,
            null,
          );

          expect(updatedSpreadSheet.read(0, 0), isNull);
          expect(
            updatedSpreadSheet.data.containsKey(0),
            isFalse,
          ); // Row should be removed if empty
          expect(
            updatedSpreadSheet,
            isNot(same(spreadSheet)),
          ); // Should be a new instance
          verify(mockDb.delete(0, 0)).called(1);
        },
      );

      test('should delete a cell and keep other cells in the row', () async {
        final initialData = {
          0: {
            0: CellData(value: 'To Delete', properties: {}),
            1: CellData(value: 'Keep Me', properties: {}),
          },
        };

        final spreadSheet = SpreadSheet(db: mockDb, data: initialData);

        when(mockDb.delete(0, 0)).thenAnswer((_) async => {});

        final updatedSpreadSheet = await spreadSheet.upsertOrDelete(0, 0, null);

        expect(updatedSpreadSheet.read(0, 0), isNull);
        expect(
          updatedSpreadSheet.read(0, 1),
          initialData[0]![1],
        ); // Other cell should remain
        expect(
          updatedSpreadSheet.data.containsKey(0),
          isTrue,
        ); // Row should not be removed
        expect(
          updatedSpreadSheet,
          isNot(same(spreadSheet)),
        ); // Should be a new instance
        verify(mockDb.delete(0, 0)).called(1);
      });

      test(
        'should return same SpreadSheet instance if deleting non-existent cell',
        () async {
          final initialData = {
            0: {0: CellData(value: 'Existing', properties: {})},
          };

          final spreadSheet = SpreadSheet(db: mockDb, data: initialData);

          // Mock DB delete to do nothing as cell doesn't exist in DB either
          when(mockDb.delete(0, 1)).thenAnswer((_) async => {});

          final updatedSpreadSheet = await spreadSheet.upsertOrDelete(
            0,
            1,
            null,
          );

          expect(updatedSpreadSheet.read(0, 0), initialData[0]![0]);
          expect(updatedSpreadSheet.read(0, 1), isNull);
          expect(
            updatedSpreadSheet,
            same(spreadSheet),
          ); // Should be the same instance
          verifyNever(
            mockDb.delete(any, any),
          ); // Should not call delete on DB if not in local data
        },
      );
    });

    test('read should return CellData if present', () {
      final cell = CellData(value: 'Test', properties: {});
      final data = {
        0: {0: cell},
      };
      final spreadSheet = SpreadSheet(db: mockDb, data: data);

      expect(spreadSheet.read(0, 0), cell);
    });

    test('read should return null if cell not present', () {
      final data = {
        0: {0: CellData(value: 'Test', properties: {})},
      };
      final spreadSheet = SpreadSheet(db: mockDb, data: data);

      expect(spreadSheet.read(0, 1), isNull);
    });

    test('operator == and hashCode should work correctly', () {
      final db1 = MockSpreadsheetDB();
      final db2 = MockSpreadsheetDB();
      final data1 = {
        0: {0: CellData(value: 'A', properties: {})},
      };
      final data3 = {
        0: {0: CellData(value: 'B', properties: {})},
      };

      final ss1 = SpreadSheet(db: db1, data: data1);
      final ss2 = SpreadSheet(db: db1, data: data1);
      final ss3 = SpreadSheet(db: db1, data: data3);
      final ss4 = SpreadSheet(db: db2, data: data1);

      expect(ss1, ss2);
      expect(ss1.hashCode, ss2.hashCode);
      expect(ss1, isNot(ss3));
      expect(ss1, isNot(ss4));
    });
  });
}
